package ca.masonx.jircc.chatabs;

public enum ChatType {
	CHAT_MESSAGE,
	ACTION_MESSAGE,
	JOIN_MESSAGE,
	PART_MESSAGE,
	QUIT_MESSAGE,
	KICK_MESSAGE,
	MODE_MESSAGE,
	NICK_MESSAGE,
	TOPIC_MESSAGE,
	UNKNOWN_MESSAGE
}
